// ══════════════════════════════════════════════════════════════
// data.js — Données AB Running Loisir v3 (saison 2026-2027)
// Refondu : système d'équivalence terrain (Route/Piste/Trail) au lieu de niveaux ski.
// Auto-régulation par RPE et modulation du volume (reprise/standard/forme).
// ══════════════════════════════════════════════════════════════

// ── INFOS CLUB (bandeau page accueil) ───────────────────────────
const infosClub = [
  {
    id: 'msg1',
    titre: '🎉 Bienvenue à la nouvelle section Running Loisir !',
    texte: "La section AB Running Loisir ouvre ses portes à tous les coureurs qui souhaitent pratiquer dans une ambiance conviviale. Mardi et jeudi 18h15 au stade La Floride. Inscriptions ouvertes.",
    dateFin: '',
    type: 'info'
  },
  {
    id: 'msg2',
    titre: '📢 Sortie montagne le 15 du mois',
    texte: "Prochaine sortie montagne prévue le 15. Départ en covoiturage depuis La Floride à 8h. Plus d'infos dans l'onglet Sorties.",
    dateFin: '',
    type: 'event'
  }
];

// ── TEXTES EXPLICATIFS CALCULATEUR ──────────────────────────────
const calculateurTextes = {
  intro: "Cette page te permet de calculer ta charge d'entraînement hebdomadaire. Remplis simplement la durée et le ressenti (RPE) de chacune de tes séances. Les calculs se font automatiquement pour t'aider à visualiser ta charge et à progresser sans te blesser.",

  rpe_titre: "Qu'est-ce que le RPE ?",
  rpe_texte: "Le RPE (Rating of Perceived Exertion, ou Effort Perçu) est une note de 1 à 10 que tu donnes à ta séance, une minute après l'avoir terminée. Cette note reflète le ressenti global : facilité respiratoire, fatigue musculaire, difficulté mentale.\n\n1-2 : très facile, comme marcher\n3-4 : facile, allure de conversation\n5-6 : modéré, respiration contrôlée\n7-8 : difficile, parler devient compliqué\n9-10 : très difficile, effort maximal",

  ua_titre: "Qu'est-ce que l'UA ?",
  ua_texte: "L'UA (Unité Arbitraire) est une mesure de la charge réelle d'une séance. C'est un simple calcul : UA = RPE × Durée (en minutes).\n\nExemple : une séance de 45 minutes ressentie à 7/10 représente 315 UA.\n\nL'intérêt ? Une semaine avec beaucoup d'UA = charge élevée, une semaine légère = UA bas. En suivant ton total hebdomadaire, tu peux progresser par paliers sans tomber dans le surentraînement.",

  bloc_titre: "La logique du bloc de 4 semaines",
  bloc_texte: "Un cycle d'entraînement bien construit suit une progression sur 4 semaines :\n\nSemaine 1 — Base : charge modérée, on pose les fondations.\nSemaine 2 — Montée : +10 à 15% d'UA par rapport à S1.\nSemaine 3 — Pic : +20 à 25% d'UA par rapport à S1 (semaine la plus dure).\nSemaine 4 — Récupération : -40% d'UA pour assimiler le travail.\n\nCette alternance charge/récupération est indispensable pour progresser sans se blesser."
};

// ── SEUILS CHARGE HEBDOMADAIRE (Option 1 — seuils conservés, libellés neutres) ──
// Les codes couleur ne reprennent plus le système ski : ils sont juste des indicateurs UI.
const chargeHebdoSeuils = [
  { max:280,  label:'Récupération',    couleur:'#7BA098', description:'Semaine de récup, reprise après course, ou décharge profonde' },
  { max:380,  label:'Modérée',         couleur:'#7BC3E5', description:'Reprise progressive, semaine légère' },
  { max:480,  label:'Soutenue',        couleur:'#3A7BBF', description:'Décharge classique, ou semaine de base modérée' },
  { max:600,  label:'Difficile',       couleur:'#1B3A6B', description:'Semaine de base ou affûtage' },
  { max:800,  label:'Très difficile',  couleur:'#E67E22', description:'Semaine de développement, charge soutenue' },
  { max:1050, label:'Pic de charge',   couleur:'#C0392B', description:'Semaine pic — la plus dure du bloc' },
  { max:9999, label:'Surcharge',       couleur:'#7B1212', description:'Au-delà du seuil — à surveiller de près' }
];

// ── TERRAINS ────────────────────────────────────────────────────
const terrainLabel = {
  // Bayonne
  halage:    {icon:'\uD83C\uDF0A',label:'Halage \u00B7 Nive',cls:'tag-sky'},
  floride:   {icon:'\u26F0\uFE0F',label:'C\u00F4te La Floride',cls:'tag-blue'},
  voulgre:   {icon:'\u26F0\uFE0F',label:'C\u00F4te Voulgre',cls:'tag-blue'},
  vw:        {icon:'\u26F0\uFE0F',label:'C\u00F4te VW',cls:'tag-blue'},
  douves:    {icon:'\uD83C\uDF3F',label:'Les Douves',cls:'tag-green'},
  intramuros:{icon:'\uD83C\uDFF0',label:'Intra-muros',cls:'tag-green'},
  stades:    {icon:'\uD83C\uDFDF',label:'Tour stades rugby',cls:'tag-sky'},
  // Anglet
  coteanglet:{icon:'\u26F0\uFE0F',label:'C\u00F4te Anglet',cls:'tag-blue'},
  girouettes:{icon:'\uD83C\uDF3F',label:'Parc Les Girouettes',cls:'tag-green'},
  chiberta:  {icon:'\uD83C\uDF32',label:'For\u00EAt Chiberta',cls:'tag-green'},
  plage:     {icon:'\uD83C\uDFD6',label:'Plage + Chiberta',cls:'tag-sky'},
  // Biarritz & montagne
  escaliers: {icon:'\uD83E\uDE9C',label:'Escaliers Biarritz',cls:'tag-ocre'},
  montagne:  {icon:'\uD83C\uDFD4',label:'Ursuya / Mondarrain',cls:'tag-rouge'},
  vvf:       {icon:'\u26F0\uFE0F',label:'C\u00F4te VVF Anglet',cls:'tag-blue'},
}

// ── PHASES (libellés UI) ────────────────────────────────────────
const phaseLabels = {
  'phase-reprise':   {label:'Reprise',cls:'phase-reprise'},
  'phase-base':      {label:'Base endurance',cls:'phase-base'},
  'phase-dev':       {label:'D\u00E9veloppement',cls:'phase-dev'},
  'phase-force':     {label:'Force / D+',cls:'phase-force'},
  'phase-prepa':     {label:'Pr\u00E9pa trail',cls:'phase-prepa'},
  'phase-precomp':   {label:'Pr\u00E9-comp\u00E9tition',cls:'phase-precomp'},
  'phase-senpereko': {label:'Objectif course',cls:'phase-event'},
  'phase-euskal':    {label:'Objectif course',cls:'phase-event'},
  'phase-recup':     {label:'R\u00E9cup\u00E9ration',cls:'phase-recup'},
  'phase-grp':       {label:'Bloc montagne',cls:'phase-montagne'},
  'phase-montagne':  {label:'Bloc montagne',cls:'phase-montagne'},
}

// ── TYPES DE SORTIES (calendrier) ───────────────────────────────
const typeLabel = {
  trail:'\uD83C\uDF3F Trail', route:'\uD83C\uDFC3 Route', rando:'\uD83E\uDD7E Rando',
  montagne:'\uD83C\uDFD4 Montagne', social:'\uD83C\uDF89 Section'
};

const typeCls = {
  trail:'type-trail', route:'type-route', rando:'type-rando',
  montagne:'type-montagne', social:'type-social'
};

// ════════════════════════════════════════════════════════════════
// SÉANCES — bibliothèque refondue (équivalence terrain)
// ════════════════════════════════════════════════════════════════
// ── BIBLIOTHÈQUE DES 80 SÉANCES (variantes Route / Piste / Trail) ──
// Chaque clé donne accès aux 3 variantes terrain + RPE + volume + notes.
// L'auto-régulation se fait par RPE et par modulation du volume (reprise/standard/forme).
const seancesData = {
  '2x8x8s_r2': {
    label:    '2×(8×8") R=2\' entre séries',
    cat:      'VMA explosive',
    rpe:      '9/10',
    route:    '—',
    piste:    '2×(8×8") sur ligne droite piste, R=2\' marche',
    trail:    '—',
    volume:   '8 reps standard · 12 si forme',
    notes:    'Travail purement neuromusculaire — explosivité maximale, récup complète obligatoire.',
  },
  'cote_20s': {
    label:    '12×20" côte (explosif court)',
    cat:      'VMA explosive',
    rpe:      '9/10',
    route:    '—',
    piste:    '—',
    trail:    '12×20" sur côte (Floride section basse)',
    volume:   '8 reprise · 12 standard · 15 si forme',
    notes:    'Côte UNIQUE : Floride section basse. Si la puissance baisse, stopper.',
  },
  'interval_court': {
    label:    'Intervalles courts (15s-20s)',
    cat:      'VMA explosive',
    rpe:      '9/10',
    route:    '12×20" R=45" trot Halage',
    piste:    '12×200m R=200m trot',
    trail:    '12×20" sentier roulant Chiberta',
    volume:   '8 reprise · 12 standard · 16 si forme',
    notes:    'Format Tabata adapté — explosivité neuromusculaire pure.',
  },
  '30s': {
    label:    'Efforts 30 secondes (VMA courte)',
    cat:      'VMA courte',
    rpe:      '8-9/10',
    route:    '10×30" R=30" trot Halage',
    piste:    '10×100m R=100m trot piste',
    trail:    '10×30" sentier roulant',
    volume:   '6 reprise · 10 standard · 14 si forme',
    notes:    'Séance neuromusculaire — jamais à fond dès le départ. Auto-régulation par RPE.',
  },
  '45s': {
    label:    'Efforts 45 secondes',
    cat:      'VMA courte',
    rpe:      '8-9/10',
    route:    '8×45" R=1\'45" Halage',
    piste:    '8×150m R=200m trot piste',
    trail:    '8×45" sentier',
    volume:   '6 reprise · 8 standard · 12 si forme',
    notes:    'Intermédiaire entre 30s et 1min — idéal aussi en côte.',
  },
  '3030': {
    label:    '30"/30" (VMA courte)',
    cat:      'VMA courte',
    rpe:      '8-9/10',
    route:    '10×30"/30" trot Halage',
    piste:    '10×100m/100m trot piste',
    trail:    '10×30"/30" sentier roulant',
    volume:   '6 reprise · 10 standard · 15 si forme',
    notes:    'Référence VMA — récup trottinée OBLIGATOIRE (jamais s\'arrêter).',
  },
  '1min': {
    label:    'Efforts 1 minute',
    cat:      'VMA courte',
    rpe:      '7-8/10',
    route:    '10×1\' R=1\'45" Halage',
    piste:    '10×400m R=200m trot piste',
    trail:    '10×1\' sentier roulant',
    volume:   '6 reprise · 10 standard · 14 si forme',
    notes:    'Base du fractionné court — tenir l\'allure sur toutes les reps.',
  },
  '8x50s_vma': {
    label:    '8×50" (VMA intermédiaire)',
    cat:      'VMA courte',
    rpe:      '8/10',
    route:    '8×50" R=2\' Halage',
    piste:    '8×200m R=200m trot piste',
    trail:    '8×50" sentier',
    volume:   '5 reprise · 8 standard · 10 si forme',
    notes:    'Durée intermédiaire entre 30" et 1min — pour ceux qui peinent sur 1min.',
  },
  '1min30': {
    label:    'Efforts 1min30',
    cat:      'VMA longue',
    rpe:      '7-8/10',
    route:    '10×1\'30 R=1\'30 trot Halage',
    piste:    '10×400m R=200m trot piste',
    trail:    '10×1\'30 sentier',
    volume:   '5 reprise · 10 standard · 12 si forme',
    notes:    'Durée idéale aussi pour côtes VW et Voulgre.',
  },
  '2min': {
    label:    'Efforts 2 minutes',
    cat:      'VMA longue',
    rpe:      '7-8/10',
    route:    '8×2\' R=2\' trot Halage',
    piste:    '8×600m R=300m trot piste',
    trail:    '8×2\' sentier roulant',
    volume:   '4 reprise · 8 standard · 10 si forme',
    notes:    'Transition VMA→seuil — rythme à maintenir sur toutes les reps.',
  },
  '3min': {
    label:    'Efforts 3 minutes (seuil-VMA)',
    cat:      'Seuil',
    rpe:      '7/10',
    route:    '6×3\' R=2\' Halage',
    piste:    '6×800m R=400m trot piste',
    trail:    '6×3\' sentier roulant',
    volume:   '3 reprise · 6 standard · 8 si forme',
    notes:    'Introduction au travail seuil — peut parler par mots courts.',
  },
  '4min': {
    label:    'Efforts 4 minutes (seuil)',
    cat:      'Seuil',
    rpe:      '6-7/10',
    route:    '5×4\' R=2\' Halage',
    piste:    '5×1000m R=400m trot piste',
    trail:    '5×4\' sentier roulant',
    volume:   '3 reprise · 5 standard · 6 si forme',
    notes:    'Allure seuil confort — base marathon/trail long.',
  },
  '5min': {
    label:    'Efforts 5 minutes (seuil)',
    cat:      'Seuil',
    rpe:      '6-7/10',
    route:    '5×5\' R=2\'30 Halage',
    piste:    '5×1200m R=400m trot piste',
    trail:    '5×5\' sentier roulant',
    volume:   '2 reprise · 5 standard · 6 si forme',
    notes:    'Séance clé marathon et trail — régularité avant tout.',
  },
  '6min': {
    label:    'Efforts 6 minutes (seuil long)',
    cat:      'Seuil',
    rpe:      '6-7/10',
    route:    '4×6\' R=3\' Halage',
    piste:    '4×1500m R=500m trot piste',
    trail:    '4×6\' sentier roulant',
    volume:   '2 reprise · 4 standard · 5 si forme',
    notes:    'Seuil long — gestion de l\'allure essentielle.',
  },
  '8min': {
    label:    'Efforts 8 minutes (allure course)',
    cat:      'Seuil',
    rpe:      '6/10',
    route:    '3×8\' R=3\' Halage',
    piste:    '3×2000m R=600m trot piste',
    trail:    '3×8\' sentier roulant',
    volume:   '2 reprise · 3 standard · 4 si forme',
    notes:    'Simulation course — reproduire exactement l\'allure cible (semi/marathon).',
  },
  '10min': {
    label:    'Efforts 10 minutes (tempo)',
    cat:      'Seuil',
    rpe:      '6/10',
    route:    '3×10\' R=3\' Halage',
    piste:    '3×2500m R=600m trot piste',
    trail:    '3×10\' sentier roulant',
    volume:   '2 reprise · 3 standard · 4 si forme',
    notes:    'Tempo — allure soutenue confortable (semi-marathon).',
  },
  '12min': {
    label:    'Efforts 12 minutes',
    cat:      'Seuil',
    rpe:      '6/10',
    route:    '2×12\' R=4\' Halage',
    piste:    '2×3000m R=800m trot piste',
    trail:    '2×12\' sentier roulant',
    volume:   '2 standard · 3 si forme',
    notes:    'Seuil long — concentration mentale clé.',
  },
  '15min': {
    label:    'Efforts 15 minutes (tempo long)',
    cat:      'Seuil',
    rpe:      '5-6/10',
    route:    '2×15\' R=5\' Halage',
    piste:    '2×3500m R=800m trot piste',
    trail:    '2×15\' sentier roulant',
    volume:   '2 standard',
    notes:    'Séance exigeante mentalement — préparer ravitaillement.',
  },
  '20min': {
    label:    'Efforts 20 minutes (seuil continu)',
    cat:      'Seuil',
    rpe:      '5-6/10',
    route:    '1×20\' continu Halage',
    piste:    '1×5000m continu piste',
    trail:    '1×20\' continu sentier',
    volume:   '1×20\' standard · 2×20\' R=5\' si forme',
    notes:    'Seuil continu — allure semi-marathon. Référence préparation.',
  },
  'pyramid_1234321': {
    label:    'Pyramide 1\'2\'3\'4\'3\'2\'1\' R=½ temps',
    cat:      'VMA/Seuil',
    rpe:      '7-8/10',
    route:    '1 passage Halage R=½ temps',
    piste:    '1 passage piste R=½ temps',
    trail:    '1 passage sentier roulant',
    volume:   '1 passage standard · + 1\'2\'3\' si forme',
    notes:    'Pyramide classique — monter en intensité sur les longs, redescendre sur les courts.',
  },
  'pyramid_1246421': {
    label:    'Pyramide 1\'2\'4\'6\'4\'2\'1\' R=½ temps',
    cat:      'VMA/Seuil',
    rpe:      '7-8/10',
    route:    '1 passage Halage',
    piste:    '1 passage piste',
    trail:    '1 passage sentier roulant',
    volume:   '1 passage standard · + 1\'2\' si forme',
    notes:    'Pyramide longue — le 6\' est la clé. Gérer l\'effort.',
  },
  'pyramid_246642': {
    label:    'Pyramide 2\'4\'6\'6\'4\'2\' R=½ temps',
    cat:      'Seuil',
    rpe:      '7/10',
    route:    '1 passage Halage',
    piste:    '1 passage piste',
    trail:    '1 passage sentier roulant',
    volume:   '1 passage standard · + 2\' si forme',
    notes:    'Double 6\' au sommet — séance longue (~26min effort).',
  },
  'pyramid_124641': {
    label:    'Pyramide 1\'2\'4\'6\'4\'1\' R=½ temps',
    cat:      'VMA/Seuil',
    rpe:      '7-8/10',
    route:    '1 passage Halage',
    piste:    '1 passage piste',
    trail:    '1 passage sentier roulant',
    volume:   '1 passage standard · + 1\'2\' si forme',
    notes:    'Variante asymétrique — montée progressive jusqu\'au 6\', descente rapide.',
  },
  'fartlek_1234441321': {
    label:    'Fartlek 1\'2\'3\'4\'4\'4\'3\'2\'1\' R=½ temps',
    cat:      'VMA/Seuil',
    rpe:      '7-8/10',
    route:    '1 passage Halage',
    piste:    '1 passage piste',
    trail:    '1 passage sentier roulant',
    volume:   '1 passage standard · + extra 1\'2\'3\' si forme',
    notes:    'Pyramide longue — 3 blocs à 4\'. Total ~29min effort.',
  },
  'fartlek_5_10_10': {
    label:    'Fartlek 5\'-10\'-10\' R~½ temps',
    cat:      'Seuil',
    rpe:      '6-7/10',
    route:    '5\'+10\'+10\' Halage',
    piste:    '5\'+10\'+10\' piste',
    trail:    '5\'+10\'+10\' sentier roulant',
    volume:   'Standard · + 5\' final si forme',
    notes:    '3 blocs longs progressifs — le 5\' active, les deux 10\' sont le cœur.',
  },
  'fartlek_3_6_6_3': {
    label:    'Fartlek 3\'6\'6\'3\' R~½ temps',
    cat:      'Seuil',
    rpe:      '7/10',
    route:    '1 passage Halage',
    piste:    '1 passage piste',
    trail:    '1 passage sentier roulant',
    volume:   '1 passage standard · + 3\' si forme',
    notes:    'Double sommet à 6\' — montée et descente symétriques.',
  },
  'fartlek_5_8_12_r3': {
    label:    'Fartlek progressif 5\'-8\'-12\' R=3\'',
    cat:      'Seuil',
    rpe:      '7/10',
    route:    '5\'+8\'+12\' Halage',
    piste:    '5\'+8\'+12\' piste',
    trail:    '5\'+8\'+12\' sentier',
    volume:   'Standard · + 5\' final si forme',
    notes:    'Volume aérobie croissant — le 12\' est le bloc clé. Total ~25min.',
  },
  'fartlek': {
    label:    'Fartlek libre',
    cat:      'Mixte',
    rpe:      '5-7/10',
    route:    '45min libre Halage/Intramuros',
    piste:    '—',
    trail:    '45min libre sentier',
    volume:   '30min reprise · 45min standard · 60min si forme',
    notes:    'Adapter au terrain et à la sensation — jamais de chrono sur les efforts.',
  },
  'fartlek_structure': {
    label:    'Fartlek structuré (2\'/2\')',
    cat:      'VMA/Seuil',
    rpe:      '6-8/10',
    route:    '6×(2\' vif / 2\' trot) Halage',
    piste:    '6×(2\' vif / 2\' trot) piste',
    trail:    '6×(2\' vif / 2\' trot) sentier',
    volume:   '4 cycles reprise · 6 standard · 8 si forme',
    notes:    'Conserver l\'allure identique sur tous les blocs.',
  },
  'fartlek_10x1_1': {
    label:    'Fartlek 10×1\'/1\' (récup trottinée)',
    cat:      'VMA',
    rpe:      '7-8/10',
    route:    '10×(1\'/1\' trot) Halage',
    piste:    '10×(1\'/1\' trot) piste',
    trail:    '10×(1\'/1\' trot) sentier',
    volume:   '6 cycles reprise · 10 standard · 12 si forme',
    notes:    'Récup ACTIVE obligatoire (trottiner, jamais s\'arrêter).',
  },
  'fartlek_10x2': {
    label:    'Fartlek 10×2\' R~1\'',
    cat:      'VMA/Seuil',
    rpe:      '7-8/10',
    route:    '10×(2\'/1\' trot) Halage',
    piste:    '10×(2\'/1\' trot) piste',
    trail:    '10×(2\'/1\' trot) sentier',
    volume:   '6 reprise · 10 standard · 12 si forme',
    notes:    'Plus exigeant que le 10×1\' — efforts plus longs.',
  },
  'fartlek_6x1_x2': {
    label:    'Fartlek 2×(6×1\'/1\')',
    cat:      'VMA',
    rpe:      '7-8/10',
    route:    '2×(6×1\'/1\') R=2\' Halage',
    piste:    '2×(6×1\'/1\') R=2\' piste',
    trail:    '2×(6×1\'/1\') R=2\' sentier',
    volume:   '1 série reprise · 2 séries standard · + 2×1\' si forme',
    notes:    'Double série — le bloc R=2min permet de maintenir la qualité.',
  },
  'fartlek_2x8x30': {
    label:    'Fartlek 2×(8×30"/30")',
    cat:      'VMA',
    rpe:      '8/10',
    route:    '2×(8×30"/30") R=2\' Halage',
    piste:    '2×(8×30"/30") R=2\' piste',
    trail:    '2×(8×30"/30") R=2\' sentier',
    volume:   '1 série reprise · 2 séries standard',
    notes:    'Double série fartlek 30/30 — tenir la qualité sur la 2e série.',
  },
  'fartlek_321_x3': {
    label:    'Fartlek 3×(3\'2\'1\') R=2\' entre séries',
    cat:      'VMA/Seuil',
    rpe:      '7-8/10',
    route:    '3×(3\'2\'1\') R=2\' Halage',
    piste:    '3×(3\'2\'1\') R=2\' piste',
    trail:    '3×(3\'2\'1\') R=2\' sentier',
    volume:   '2 séries reprise · 3 séries standard · + 1× si forme',
    notes:    'Pyramide inverse répétée — chaque série descend (3\'/2\'/1\').',
  },
  '30s_r_decrements': {
    label:    '30" R= 4\'-3\'-2\' (récup décroissante)',
    cat:      'VMA',
    rpe:      '8-9/10',
    route:    '5×30" R décroissante Halage',
    piste:    '5×100m R décroissante piste',
    trail:    '5×30" R décroissante sentier',
    volume:   '3 reprise · 5 standard · 7 si forme',
    notes:    'La récup diminue au fil — simulation fin de course.',
  },
  '45_45_puis_45_30': {
    label:    '5×45"/45" + 5×45"/30"',
    cat:      'VMA',
    rpe:      '8/10',
    route:    '5×45"/45" + 5×45"/30" Halage',
    piste:    '5×45"/45" + 5×45"/30" piste',
    trail:    '5×45"/45" + 5×45"/30" sentier',
    volume:   '3+3 reprise · 5+5 standard',
    notes:    'Double bloc avec récup décroissante — simulation fin de course.',
  },
  '8x30_30_r2_6x1_1': {
    label:    '8×30"/30" R=2\' + 6×1\'/1\'',
    cat:      'VMA',
    rpe:      '8/10',
    route:    '8×30"/30" + 6×1\'/1\' Halage',
    piste:    '8×30"/30" + 6×1\'/1\' piste',
    trail:    '8×30"/30" + 6×1\'/1\' sentier',
    volume:   '5+4 reprise · 8+6 standard · 8+8 si forme',
    notes:    'Double bloc VMA — les 30/30 chauffent, les 1\'/1\' maintiennent la charge.',
  },
  '2x8x30_30_r3': {
    label:    '2×(8×30"/30") R=3\' entre séries',
    cat:      'VMA',
    rpe:      '8/10',
    route:    '2×(8×30"/30") Halage',
    piste:    '2×(8×30"/30") piste',
    trail:    '2×(8×30"/30") sentier',
    volume:   '1 série reprise · 2 séries standard · + 4× si forme',
    notes:    'La 2e série doit être aussi bonne que la 1re.',
  },
  '2x6x30_30_r130': {
    label:    '2×(6×30"/30") R=1\'30"',
    cat:      'VMA',
    rpe:      '8/10',
    route:    '2×(6×30"/30") Halage',
    piste:    '2×(6×30"/30") piste',
    trail:    '2×(6×30"/30") sentier',
    volume:   '1 série reprise · 2 séries standard',
    notes:    'Version plus courte que le 2×8 — adapté quand moins de temps.',
  },
  '2x8x2020': {
    label:    '2×(8×20"/20") R=2\'',
    cat:      'VMA',
    rpe:      '8-9/10',
    route:    '2×(8×20"/20") Halage',
    piste:    '2×(8×20"/20") piste',
    trail:    '2×(8×20"/20") sentier',
    volume:   '1 série reprise · 2 séries standard · + 4× si forme',
    notes:    'Intervalles très courts en double série — repos 2min permet la qualité.',
  },
  '5x30_8x1_5x30': {
    label:    '5×30"/30" + 8×1\'/1\' + 5×30"/30"',
    cat:      'VMA',
    rpe:      '8/10',
    route:    '5+8+5 Halage',
    piste:    '5+8+5 piste',
    trail:    '5+8+5 sentier roulant',
    volume:   '3+5+3 reprise · 5+8+5 standard · 5+10+5 si forme',
    notes:    'Triple bloc symétrique — courts/longs/courts. Les 30" finaux sont les plus durs.',
  },
  'vitesse_8x100_5x200': {
    label:    '8×100m R3\' + 5×200m R3\'',
    cat:      'Vitesse',
    rpe:      '8-9/10',
    route:    '—',
    piste:    '8×100m + 5×200m piste',
    trail:    '—',
    volume:   '6+3 reprise · 8+5 standard',
    notes:    'Deux blocs : 100m mécanique de course, 200m endurance de vitesse.',
  },
  'vitesse_6x300_4x400': {
    label:    '6×300m + 4×400m',
    cat:      'Vitesse/VMA',
    rpe:      '8/10',
    route:    '—',
    piste:    '6×300m + 4×400m piste',
    trail:    '—',
    volume:   '4+2 reprise · 6+4 standard',
    notes:    'Référence puissance aérobie. Tenir l\'allure identique sur tous les 300m.',
  },
  'vitesse_2x6x200': {
    label:    '2×(6×200m) R=200m + 3-4\' entre séries',
    cat:      'Vitesse',
    rpe:      '8-9/10',
    route:    '—',
    piste:    '2×(6×200m) piste',
    trail:    '—',
    volume:   '1 série reprise · 2 séries standard',
    notes:    'Blocs répétés — la 2e série est plus difficile que la 1re. C\'est normal.',
  },
  'vitesse_6x100_5x200': {
    label:    '6×100m + 5×200m',
    cat:      'Vitesse',
    rpe:      '8-9/10',
    route:    '—',
    piste:    '6×100m + 5×200m piste',
    trail:    '—',
    volume:   '4+3 reprise · 6+5 standard',
    notes:    'Activation et vitesse combinées — les 100m préparent le neuromusculaire.',
  },
  'vitesse_6x100_4x200_etc': {
    label:    '6×100m + 4×200m + 2×300m + 1×400m',
    cat:      'Vitesse/VMA',
    rpe:      '8/10',
    route:    '—',
    piste:    'Progression piste',
    trail:    '—',
    volume:   'Demi-volume reprise · volume complet standard',
    notes:    'Volume et distance croissants — gérer l\'énergie dès les 100m.',
  },
  'vitesse_5x100_veille': {
    label:    '5×100m (séance veille de course)',
    cat:      'Vitesse',
    rpe:      '6-7/10',
    route:    '—',
    piste:    '5×100m piste',
    trail:    '—',
    volume:   '4 reps reprise · 5 standard',
    notes:    'Activation pré-compétition — JAMAIS épuisant. Réveiller les jambes.',
  },
  'piste_10x400_r200': {
    label:    '10×400m piste R=200m trottiné',
    cat:      'VMA',
    rpe:      '7-8/10',
    route:    '—',
    piste:    '10×400m R=200m trot piste',
    trail:    '—',
    volume:   '6 reprise · 10 standard',
    notes:    'Séance de référence piste. Tenir la même allure sur tous les 400m.',
  },
  'piste_10x300_r100': {
    label:    '10×300m piste R=100m trottiné',
    cat:      'VMA',
    rpe:      '8/10',
    route:    '—',
    piste:    '10×300m R=100m trot piste',
    trail:    '—',
    volume:   '6 reprise · 10 standard',
    notes:    'Récup très courte — séance volume intense.',
  },
  'piste_10x200_r100': {
    label:    '10×200m piste R=100m trottiné',
    cat:      'Vitesse-end.',
    rpe:      '8-9/10',
    route:    '—',
    piste:    '10×200m R=100m trot piste',
    trail:    '—',
    volume:   '6 reprise · 10 standard',
    notes:    'Vitesse-endurance — récup courte qui force à gérer l\'allure.',
  },
  'piste_5x200_5x300_r400': {
    label:    '5×200m + 5×300m R=400m trottiné',
    cat:      'Vitesse/VMA',
    rpe:      '8/10',
    route:    '—',
    piste:    '5×200m + 5×300m piste',
    trail:    '—',
    volume:   '3+3 reprise · 5+5 standard',
    notes:    'Distances croissantes avec grande récup — les 300m avec jambes chargées.',
  },
  'piste_progression_100_500': {
    label:    'Progression 5×100 + 4×200 + 3×300 + 2×400 + 1×500',
    cat:      'Vitesse/VMA',
    rpe:      '8/10',
    route:    '—',
    piste:    'Progression piste',
    trail:    '—',
    volume:   'Demi-volume reprise · volume complet standard',
    notes:    'Pyramide croissante ~3500m. Partir conservateur sur les 100m.',
  },
  'piste_5x100_4x200_3x300_2x400': {
    label:    '5×100 + 4×200 + 3×300 + 2×400',
    cat:      'Vitesse/VMA',
    rpe:      '8/10',
    route:    '—',
    piste:    'Progression piste',
    trail:    '—',
    volume:   'Demi-volume reprise · volume complet standard',
    notes:    'Version sans le 500m final — plus abordable, idéale en milieu de prépa.',
  },
  '3x15_r5': {
    label:    '3×15\' R=5\'',
    cat:      'Seuil long',
    rpe:      '6-7/10',
    route:    '3×15\' R=5\' Halage',
    piste:    '3×15\' R=5\' piste',
    trail:    '3×15\' R=5\' sentier roulant',
    volume:   '2×12\' reprise · 3×15\' standard',
    notes:    'Séance la plus exigeante mentalement. Tenir l\'allure sur le 3e bloc est l\'objectif.',
  },
  '8x3_r130': {
    label:    '8×3\' R=1\'30"',
    cat:      'Seuil',
    rpe:      '7/10',
    route:    '8×3\' R=1\'30" Halage',
    piste:    '8×800m R=400m trot piste',
    trail:    '8×3\' sentier roulant',
    volume:   '5 reprise · 8 standard',
    notes:    'Volume au seuil — récup courte qui impose de gérer l\'allure.',
  },
  '10x3030_v2': {
    label:    '10×30"/30" (version terrain)',
    cat:      'VMA',
    rpe:      '8/10',
    route:    '10×30"/30" Halage',
    piste:    '10×100m/100m piste',
    trail:    '10×30"/30" sentier ou côte',
    volume:   '6 reprise · 10 standard · 15 si forme',
    notes:    'Variante terrain — peut se faire en côte (30s montée / 30s descente récup).',
  },
  '3x7_r130': {
    label:    '3×7\' R=1\'30"',
    cat:      'Seuil',
    rpe:      '7/10',
    route:    '3×7\' R=1\'30" Halage',
    piste:    '3×1800m R=400m trot piste',
    trail:    '3×7\' sentier roulant',
    volume:   '2 reprise · 3 standard',
    notes:    'Seuil moyen — récup courte qui impose de gérer l\'allure dès le départ.',
  },
  '3x8_r1': {
    label:    '3×8\' R=1\'',
    cat:      'Seuil',
    rpe:      '7/10',
    route:    '3×8\' R=1\' Halage',
    piste:    '3×2000m R=300m trot piste',
    trail:    '3×8\' sentier roulant',
    volume:   '2 reprise · 3 standard · + 4\' final si forme',
    notes:    'Seuil long avec récup TRÈS courte — gestion fine. Si impossible : passer à R=2\'.',
  },
  '5x1000_halage': {
    label:    '5×1000m Halage R~2-3\'',
    cat:      'Seuil',
    rpe:      '6-7/10',
    route:    '5×1000m R=2\'30" Halage',
    piste:    '5×1000m R=2\'30" piste',
    trail:    '5×1000m sentier (Chiberta plat)',
    volume:   '3 reprise · 5 standard · + 1×500 si forme',
    notes:    'Séance reine semi/marathon. Tenir exactement la même allure sur tous les 1000m.',
  },
  '4x2000_r2': {
    label:    '4×2000m R=2\'',
    cat:      'Seuil long',
    rpe:      '6-7/10',
    route:    '4×2000m R=2\' Halage',
    piste:    '4×2000m R=2\' piste',
    trail:    '4×2000m sentier (Chiberta plat)',
    volume:   '2 reprise · 4 standard',
    notes:    'Seuil long — chaque 2000m dure ~8-10min. Réservé aux phases de prépa compétition.',
  },
  'allure_marathon': {
    label:    'Sortie allure marathon',
    cat:      'Allure spécifique',
    rpe:      '6-7/10',
    route:    '1h15 allure marathon Halage',
    piste:    '—',
    trail:    '—',
    volume:   '45min reprise · 1h15 standard · 1h30 si forme',
    notes:    'Pratiquer l\'allure cible en conditions réelles — Halage idéal car régulier.',
  },
  'allure_semi': {
    label:    'Sortie allure semi',
    cat:      'Allure spécifique',
    rpe:      '7/10',
    route:    '1h allure semi Halage',
    piste:    '—',
    trail:    '—',
    volume:   '30min reprise · 1h standard · 1h15 si forme',
    notes:    'Allure semi — Halage marqué au km idéal pour calibrer.',
  },
  'sortie_longue': {
    label:    'Sortie longue endurance',
    cat:      'Endurance',
    rpe:      '3-4/10',
    route:    '1h30 EF Halage/route',
    piste:    '—',
    trail:    '1h30 EF Chiberta/Douves/sentiers',
    volume:   '1h reprise · 1h30 standard · 2h+ si forme',
    notes:    'JAMAIS > 80% FCmax — base aérobie fondamentale. Conversation possible.',
  },
  'sortie_recup': {
    label:    'Sortie récupération active',
    cat:      'Récupération',
    rpe:      '2-3/10',
    route:    '50min très douce route',
    piste:    '—',
    trail:    '50min très douce sentier',
    volume:   '40min reprise · 50min standard · 1h si forme',
    notes:    'Lendemain de séance intensive — JAMAIS de pression. Sortie sociale par excellence.',
  },
  'cote': {
    label:    'Côtes (montée générique)',
    cat:      'Force aérobie',
    rpe:      '7-9/10',
    route:    '—',
    piste:    '—',
    trail:    'Selon longueur de la côte choisie',
    volume:   '6 reprise · 10 standard · 14 si forme',
    notes:    'Adapter à la longueur. PPG OBLIGATOIRE en début de séance.',
  },
  'cote_30s': {
    label:    'Côtes courtes 30s — La Floride',
    cat:      'Force-vitesse',
    rpe:      '9/10',
    route:    '—',
    piste:    '—',
    trail:    '10×30" Côte La Floride',
    volume:   '6 reprise · 10 standard · 14 si forme',
    notes:    'Côte UNIQUE : La Floride. PPG OBLIGATOIRE avant. Genoux hauts, bras actifs.',
  },
  'cote_40s': {
    label:    'Côtes 10×40" — La Floride',
    cat:      'Force-vitesse',
    rpe:      '8-9/10',
    route:    '—',
    piste:    '—',
    trail:    '10×40" Côte La Floride',
    volume:   '6 reprise · 10 standard · 12 si forme',
    notes:    'Côte UNIQUE : La Floride. PPG avant.',
  },
  'cote_45s': {
    label:    'Côtes 12×45" — Floride ou VW',
    cat:      'Force-vitesse',
    rpe:      '8-9/10',
    route:    '—',
    piste:    '—',
    trail:    '12×45" Côte Floride OU VW',
    volume:   '8 reprise · 12 standard · 15 si forme',
    notes:    'Côte UNIQUE par séance (Floride OU VW). PPG avant.',
  },
  'cote_1min': {
    label:    'Côtes 1 minute — VW',
    cat:      'Force aérobie',
    rpe:      '8-9/10',
    route:    '—',
    piste:    '—',
    trail:    '8×1\' Côte VW',
    volume:   '5 reprise · 8 standard · 10 si forme',
    notes:    'Côte UNIQUE : VW. PPG avant. Maintenir la même allure sur toutes les répétitions.',
  },
  'cote_8x1_vw': {
    label:    'Côtes 8×1\' — VW (variante)',
    cat:      'Force aérobie',
    rpe:      '8-9/10',
    route:    '—',
    piste:    '—',
    trail:    '8×1\' Côte VW',
    volume:   '5 reprise · 8 standard · 10 si forme',
    notes:    'Variante du cote_1min — focus VW.',
  },
  'cote_10x1_girouettes': {
    label:    'Côtes 10×1\' R=45" — Girouettes',
    cat:      'Force aérobie',
    rpe:      '8/10',
    route:    '—',
    piste:    '—',
    trail:    '10×1\' Parc Les Girouettes Anglet',
    volume:   '6 reprise · 10 standard · 12 si forme',
    notes:    'Circuit naturel Girouettes — récup courte 45". Plus exigeant que côtes classiques.',
  },
  'cote_1min30': {
    label:    'Côtes 1min30 — VW ou Voulgre',
    cat:      'Force aérobie',
    rpe:      '8/10',
    route:    '—',
    piste:    '—',
    trail:    '6×1\'30 Côte VW OU Voulgre',
    volume:   '4 reprise · 6 standard · 10 si forme',
    notes:    'Côte UNIQUE par séance. PPG avant. Descente : petits pas, genoux fléchis.',
  },
  'cote_2min': {
    label:    'Côtes 2 minutes — Voulgre',
    cat:      'Force aérobie',
    rpe:      '7-8/10',
    route:    '—',
    piste:    '—',
    trail:    '6×2\' Côte Voulgre',
    volume:   '4 reprise · 6 standard · 8 si forme',
    notes:    'Côte UNIQUE : Voulgre. PPG avant. Séance phare trail — focus aussi sur descente.',
  },
  'cote_long': {
    label:    'Côtes longues 3-10min — montagne',
    cat:      'Force aérobie',
    rpe:      '6-8/10',
    route:    '—',
    piste:    '—',
    trail:    'Côtes longues Ursuya/Mondarrain',
    volume:   '3 reprise · 5 standard · 6 si forme',
    notes:    'Réservé aux sorties montagne — adapter au dénivelé. PPG avant.',
  },
  'cote_vvf_pyramide': {
    label:    'Côtes VVF Anglet — Pyramide complète',
    cat:      'Force-vitesse',
    rpe:      '8-9/10',
    route:    '—',
    piste:    '—',
    trail:    'Pyramide côte VVF Anglet (3×20" 3×40" 6×1\' 3×40" 3×20")',
    volume:   '1 passage standard · + 3×20" si forme',
    notes:    'Côte UNIQUE : VVF. PPG avant. Pyramide = 15 montées.',
  },
  'escaliers': {
    label:    'Escaliers — Côte des Basques',
    cat:      'Force-vitesse',
    rpe:      '8/10',
    route:    '—',
    piste:    '—',
    trail:    'Escaliers Biarritz Côte des Basques',
    volume:   '3 blocs reprise · 4 blocs standard · 5 blocs si forme',
    notes:    'Descente OBLIGATOIREMENT lente — fort impact excentrique quadriceps. PPG avant.',
  },
  'circuit_douves': {
    label:    '6×Circuit Les Douves R=1\'30"',
    cat:      'Trail spécifique',
    rpe:      '7-8/10',
    route:    '—',
    piste:    '—',
    trail:    '6×Circuit Les Douves Bayonne',
    volume:   '4 reprise · 6 standard · 6+2 si forme',
    notes:    'Circuit fartlek naturel — le terrain dicte l\'effort. Accélérer dans montées et lignes droites.',
  },
  'fartlek_pyramid_girouettes': {
    label:    'Pyramide 1\'2\'3\'4\'4\'4\'3\'2\'1\' Girouettes',
    cat:      'Trail spécifique',
    rpe:      '7-8/10',
    route:    '—',
    piste:    '—',
    trail:    'Pyramide circuit Girouettes Anglet',
    volume:   '1 passage standard · + 1\'2\' si forme',
    notes:    'Pyramide longue circuit Girouettes — terrain naturel technique.',
  },
  'descente': {
    label:    'Travail de descente technique',
    cat:      'Technique trail',
    rpe:      '5-6/10',
    route:    '—',
    piste:    '—',
    trail:    'Descentes techniques Chiberta/Voulgre',
    volume:   '5 passages reprise · 8 standard · 10 si forme',
    notes:    'Petits pas, regard loin, genoux fléchis — clé anti-blessure.',
  },
  'ppg_seance': {
    label:    'Séance PPG dédiée',
    cat:      'Renforcement',
    rpe:      '5-6/10',
    route:    '—',
    piste:    '—',
    trail:    '—',
    volume:   '2 séries reprise · 3 standard · 4 si forme',
    notes:    'Faire AVANT la course OU >6h après. Voir onglet "Exercices PPG".',
  },
};

// ════════════════════════════════════════════════════════════════
// OBJECTIFS-REPÈRES SAISON
// ════════════════════════════════════════════════════════════════
// ── OBJECTIFS-REPÈRES SAISON 2026-2027 ──
// Repères pour la dynamique annuelle. Chacun gère son calendrier perso.
const objectifsCalendrier = [
  { sem: 13, nom: 'Marathon La Rochelle', date: '2026-11-29', type: 'route', icon: '🏆' },
  { sem: 27, nom: 'France de Cross', date: '2027-03-07', type: 'cross', icon: '🏆' },
  { sem: 28, nom: 'Senpereko Trail', date: '2027-03-14', type: 'trail', icon: '🏆' },
  { sem: 33, nom: 'Semi-Marathon Saint-Sébastien', date: '2027-04-18', type: 'route', icon: '🏆' },
  { sem: 35, nom: 'Marathon Biarritz', date: '2027-05-02', type: 'route', icon: '🏆' },
  { sem: 36, nom: 'Euskal Raid (Ascension)', date: '2027-05-08', type: 'trail', icon: '🏆' },
  { sem: 44, nom: 'Saison Trails Pays Basque (pic)', date: '2027-06-28', type: 'trail', icon: '🏆' },
];

// ════════════════════════════════════════════════════════════════
// PROGRAMME 52 SEMAINES
// ════════════════════════════════════════════════════════════════
// ── PROGRAMME 52 SEMAINES — Saison 2026-2027 ──
// S1 = lundi 31 août 2026. Tronc commun route/trail.
// Chaque semaine pointe vers les clés de seancesData (ex. "5x1000_halage").
// Champs `we_route` et `we_trail` : variantes de sortie WE — chacun choisit selon son objectif.
const programme = [
  {
    sem: 1,
    date: '31/08/2026',
    mois: 'Août',
    phase: 'Reprise',
    phaseClass: 'phase-reprise',
    mardi: { key: 'sortie_recup', titre: 'Sortie récupération active', terrain: 'halage' },
    jeudi: { key: 'fartlek', titre: 'Fartlek libre', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 450,
    decharge: true,
    objectif: null,
    notes: 'Reprise très douce — accueil nouveaux licenciés. Pas d\'intensité. Focus convivialité.',
  },
  {
    sem: 2,
    date: '07/09/2026',
    mois: 'Sept',
    phase: 'Base',
    phaseClass: 'phase-base',
    mardi: { key: '30s', titre: 'Efforts 30 secondes (VMA courte)', terrain: 'halage' },
    jeudi: { key: 'sortie_recup', titre: 'Sortie récupération active', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 650,
    decharge: false,
    objectif: null,
    notes: 'Saison FFA officiellement ouverte. Réintroduction VMA très progressive.',
  },
  {
    sem: 3,
    date: '14/09/2026',
    mois: 'Sept',
    phase: 'Base',
    phaseClass: 'phase-base',
    mardi: { key: 'cote_30s', titre: 'Côtes courtes 30s — La Floride', terrain: 'floride' },
    jeudi: { key: '5min', titre: 'Efforts 5 minutes (seuil)', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 780,
    decharge: false,
    objectif: null,
    notes: 'Intro côtes (Floride). PPG obligatoire avant côtes. Premier seuil moyen.',
  },
  {
    sem: 4,
    date: '21/09/2026',
    mois: 'Sept',
    phase: 'Décharge',
    phaseClass: 'phase-recup',
    mardi: { key: 'sortie_recup', titre: 'Sortie récupération active', terrain: 'halage' },
    jeudi: { key: 'fartlek', titre: 'Fartlek libre', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 470,
    decharge: true,
    objectif: null,
    notes: 'Décharge — assimilation. Volume de la sortie longue maintenu, intensité coupée.',
  },
  {
    sem: 5,
    date: '28/09/2026',
    mois: 'Sept',
    phase: 'Développement',
    phaseClass: 'phase-dev',
    mardi: { key: '1min', titre: 'Efforts 1 minute', terrain: 'halage' },
    jeudi: { key: '5min', titre: 'Efforts 5 minutes (seuil)', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 830,
    decharge: false,
    objectif: null,
    notes: 'Bloc spécifique marathon. VMA courte + seuil. Volume sortie longue ↑.',
  },
  {
    sem: 6,
    date: '05/10/2026',
    mois: 'Oct',
    phase: 'Développement',
    phaseClass: 'phase-dev',
    mardi: { key: 'cote_45s', titre: 'Côtes 12×45" — Floride ou VW', terrain: 'floride' },
    jeudi: { key: '6min', titre: 'Efforts 6 minutes (seuil long)', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 860,
    decharge: false,
    objectif: null,
    notes: 'Côtes Floride/VW. PPG obligatoire. Seuil long.',
  },
  {
    sem: 7,
    date: '12/10/2026',
    mois: 'Oct',
    phase: 'Développement',
    phaseClass: 'phase-dev',
    mardi: { key: '3030', titre: '30"/30" (VMA courte)', terrain: 'halage' },
    jeudi: { key: '8min', titre: 'Efforts 8 minutes (allure course)', terrain: 'halage' },
    we_route: { key: 'allure_marathon', titre: 'Sortie allure marathon' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 920,
    decharge: false,
    objectif: null,
    notes: 'VMA + allure spécifique marathon. Test allure cible.',
  },
  {
    sem: 8,
    date: '19/10/2026',
    mois: 'Oct',
    phase: 'Décharge',
    phaseClass: 'phase-recup',
    mardi: { key: 'fartlek', titre: 'Fartlek libre', terrain: 'halage' },
    jeudi: { key: 'sortie_recup', titre: 'Sortie récupération active', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 480,
    decharge: true,
    objectif: null,
    notes: 'Décharge mi-bloc — réassimilation avant montée en charge.',
  },
  {
    sem: 9,
    date: '26/10/2026',
    mois: 'Oct',
    phase: 'Spécifique',
    phaseClass: 'phase-precomp',
    mardi: { key: '5x1000_halage', titre: '5×1000m Halage R~2-3\'', terrain: 'halage' },
    jeudi: { key: 'cote_1min30', titre: 'Côtes 1min30 — VW ou Voulgre', terrain: 'voulgre' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 950,
    decharge: false,
    objectif: null,
    notes: 'Séance reine 5×1000m. Côtes 1\'30 VW/Voulgre.',
  },
  {
    sem: 10,
    date: '02/11/2026',
    mois: 'Nov',
    phase: 'Spécifique',
    phaseClass: 'phase-precomp',
    mardi: { key: '8x3_r130', titre: '8×3\' R=1\'30"', terrain: 'halage' },
    jeudi: { key: '10min', titre: 'Efforts 10 minutes (tempo)', terrain: 'halage' },
    we_route: { key: 'allure_marathon', titre: 'Sortie allure marathon' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 980,
    decharge: false,
    objectif: null,
    notes: 'Volume seuil maximal. Test allure marathon 1h15.',
  },
  {
    sem: 11,
    date: '09/11/2026',
    mois: 'Nov',
    phase: 'Affûtage',
    phaseClass: 'phase-precomp',
    mardi: { key: '3x15_r5', titre: '3×15\' R=5\'', terrain: 'halage' },
    jeudi: { key: 'fartlek_structure', titre: 'Fartlek structuré (2\'/2\')', terrain: 'halage' },
    we_route: { key: 'allure_marathon', titre: 'Sortie allure marathon' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 870,
    decharge: false,
    objectif: null,
    notes: 'Avant-dernière semaine — début affûtage. Volume baisse, intensité maintenue.',
  },
  {
    sem: 12,
    date: '16/11/2026',
    mois: 'Nov',
    phase: 'Affûtage',
    phaseClass: 'phase-precomp',
    mardi: { key: '5x1000_halage', titre: '5×1000m Halage R~2-3\'', terrain: 'halage' },
    jeudi: { key: 'fartlek', titre: 'Fartlek libre', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 640,
    decharge: false,
    objectif: null,
    notes: 'Semaine d\'affûtage — séance courte mardi, footings légers, volume divisé par 2.',
  },
  {
    sem: 13,
    date: '23/11/2026',
    mois: 'Nov',
    phase: 'Compétition',
    phaseClass: 'phase-event',
    mardi: { key: 'vitesse_5x100_veille', titre: '5×100m (séance veille de course)', terrain: 'stades' },
    jeudi: { key: '—', titre: '—', terrain: 'halage' },
    we_route: { key: '—', titre: '—' },
    we_trail: { key: '—', titre: '—' },
    ua: 420,
    decharge: true,
    objectif: '🏆 Marathon La Rochelle (29/11)',
    notes: 'Mardi activation, jeudi repos, course dimanche.',
  },
  {
    sem: 14,
    date: '30/11/2026',
    mois: 'Nov',
    phase: 'Récupération',
    phaseClass: 'phase-recup',
    mardi: { key: '—', titre: '—', terrain: 'halage' },
    jeudi: { key: 'sortie_recup', titre: 'Sortie récupération active', terrain: 'halage' },
    we_route: { key: 'sortie_recup', titre: 'Sortie récupération active' },
    we_trail: { key: 'sortie_recup', titre: 'Sortie récupération active' },
    ua: 320,
    decharge: true,
    objectif: null,
    notes: 'Post-marathon — récup totale. Aucune intensité. Footings très doux, étirements.',
  },
  {
    sem: 15,
    date: '07/12/2026',
    mois: 'Déc',
    phase: 'Reprise',
    phaseClass: 'phase-reprise',
    mardi: { key: 'sortie_recup', titre: 'Sortie récupération active', terrain: 'halage' },
    jeudi: { key: 'fartlek', titre: 'Fartlek libre', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 500,
    decharge: true,
    objectif: null,
    notes: 'Reprise progressive — pas d\'intensité encore. Volume modéré.',
  },
  {
    sem: 16,
    date: '14/12/2026',
    mois: 'Déc',
    phase: 'Base',
    phaseClass: 'phase-base',
    mardi: { key: '30s', titre: 'Efforts 30 secondes (VMA courte)', terrain: 'halage' },
    jeudi: { key: '5min', titre: 'Efforts 5 minutes (seuil)', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 720,
    decharge: false,
    objectif: null,
    notes: 'Réintroduction VMA. Préparation au bloc cross.',
  },
  {
    sem: 17,
    date: '21/12/2026',
    mois: 'Déc',
    phase: 'Trêve Noël',
    phaseClass: 'phase-recup',
    mardi: { key: '—', titre: '—', terrain: 'halage' },
    jeudi: { key: '—', titre: '—', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 300,
    decharge: true,
    objectif: null,
    notes: '🎄 Trêve de Noël — pas d\'entraînement club. Footing libre 1×/sem si motivation.',
  },
  {
    sem: 18,
    date: '28/12/2026',
    mois: 'Déc',
    phase: 'Trêve Noël',
    phaseClass: 'phase-recup',
    mardi: { key: '—', titre: '—', terrain: 'halage' },
    jeudi: { key: '—', titre: '—', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 300,
    decharge: true,
    objectif: null,
    notes: '🎄 Trêve de Noël — reprise douce fin de semaine.',
  },
  {
    sem: 19,
    date: '04/01/2027',
    mois: 'Janv',
    phase: 'Bloc cross',
    phaseClass: 'phase-force',
    mardi: { key: 'cote_30s', titre: 'Côtes courtes 30s — La Floride', terrain: 'floride' },
    jeudi: { key: '3030', titre: '30"/30" (VMA courte)', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'circuit_douves', titre: '6×Circuit Les Douves R=1\'30"' },
    ua: 870,
    decharge: false,
    objectif: null,
    notes: 'Reprise post-Noël intensité ↑. VMA courte + côtes Floride. Trail : circuit Douves.',
  },
  {
    sem: 20,
    date: '11/01/2027',
    mois: 'Janv',
    phase: 'Bloc cross',
    phaseClass: 'phase-force',
    mardi: { key: '1min', titre: 'Efforts 1 minute', terrain: 'halage' },
    jeudi: { key: 'cote_45s', titre: 'Côtes 12×45" — Floride ou VW', terrain: 'floride' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 900,
    decharge: false,
    objectif: null,
    notes: 'VMA + côtes — focus puissance aérobie. Cross régionaux fin janv.',
  },
  {
    sem: 21,
    date: '18/01/2027',
    mois: 'Janv',
    phase: 'Bloc cross',
    phaseClass: 'phase-force',
    mardi: { key: 'fartlek_10x1_1', titre: 'Fartlek 10×1\'/1\' (récup trottinée)', terrain: 'halage' },
    jeudi: { key: 'cote_1min', titre: 'Côtes 1 minute — VW', terrain: 'vw' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'circuit_douves', titre: '6×Circuit Les Douves R=1\'30"' },
    ua: 920,
    decharge: false,
    objectif: null,
    notes: 'Fartlek + côtes VW. Spécificité cross : changements de rythme.',
  },
  {
    sem: 22,
    date: '25/01/2027',
    mois: 'Janv',
    phase: 'Décharge',
    phaseClass: 'phase-recup',
    mardi: { key: 'sortie_recup', titre: 'Sortie récupération active', terrain: 'halage' },
    jeudi: { key: 'fartlek', titre: 'Fartlek libre', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 490,
    decharge: true,
    objectif: null,
    notes: 'Décharge — assimilation bloc cross.',
  },
  {
    sem: 23,
    date: '01/02/2027',
    mois: 'Févr',
    phase: 'Bloc cross',
    phaseClass: 'phase-force',
    mardi: { key: '2x8x30_30_r3', titre: '2×(8×30"/30") R=3\' entre séries', terrain: 'halage' },
    jeudi: { key: 'cote_45s', titre: 'Côtes 12×45" — Floride ou VW', terrain: 'floride' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'fartlek_pyramid_girouettes', titre: 'Pyramide 1\'2\'3\'4\'4\'4\'3\'2\'1\' Girouettes' },
    ua: 940,
    decharge: false,
    objectif: null,
    notes: 'Double série VMA + côtes. Trail : pyramide Girouettes.',
  },
  {
    sem: 24,
    date: '08/02/2027',
    mois: 'Févr',
    phase: 'Bloc cross',
    phaseClass: 'phase-force',
    mardi: { key: 'piste_10x400_r200', titre: '10×400m piste R=200m trottiné', terrain: 'stades' },
    jeudi: { key: '3x7_r130', titre: '3×7\' R=1\'30"', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'circuit_douves', titre: '6×Circuit Les Douves R=1\'30"' },
    ua: 970,
    decharge: false,
    objectif: null,
    notes: 'Piste 10×400 + seuil. Spécificité cross/Senpereko.',
  },
  {
    sem: 25,
    date: '15/02/2027',
    mois: 'Févr',
    phase: 'Bloc cross',
    phaseClass: 'phase-force',
    mardi: { key: 'fartlek_321_x3', titre: 'Fartlek 3×(3\'2\'1\') R=2\' entre séries', terrain: 'halage' },
    jeudi: { key: 'cote_1min30', titre: 'Côtes 1min30 — VW ou Voulgre', terrain: 'voulgre' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 920,
    decharge: false,
    objectif: null,
    notes: 'Fartlek pyramide inverse + côtes 1\'30 Voulgre.',
  },
  {
    sem: 26,
    date: '22/02/2027',
    mois: 'Févr',
    phase: 'Affûtage',
    phaseClass: 'phase-precomp',
    mardi: { key: 'piste_10x300_r100', titre: '10×300m piste R=100m trottiné', terrain: 'stades' },
    jeudi: { key: 'fartlek_structure', titre: 'Fartlek structuré (2\'/2\')', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'circuit_douves', titre: '6×Circuit Les Douves R=1\'30"' },
    ua: 730,
    decharge: false,
    objectif: null,
    notes: 'Affûtage avant France cross / Senpereko. Volume ↓, intensité maintenue.',
  },
  {
    sem: 27,
    date: '01/03/2027',
    mois: 'Mars',
    phase: 'Compétition',
    phaseClass: 'phase-event',
    mardi: { key: 'vitesse_5x100_veille', titre: '5×100m (séance veille de course)', terrain: 'stades' },
    jeudi: { key: 'sortie_recup', titre: 'Sortie récupération active', terrain: 'halage' },
    we_route: { key: '—', titre: '—' },
    we_trail: { key: '—', titre: '—' },
    ua: 430,
    decharge: true,
    objectif: '🏆 France de Cross (07/03)',
    notes: 'Activation mardi, repos jeudi, course dimanche.',
  },
  {
    sem: 28,
    date: '08/03/2027',
    mois: 'Mars',
    phase: 'Compétition',
    phaseClass: 'phase-event',
    mardi: { key: 'sortie_recup', titre: 'Sortie récupération active', terrain: 'halage' },
    jeudi: { key: 'vitesse_5x100_veille', titre: '5×100m (séance veille de course)', terrain: 'stades' },
    we_route: { key: '—', titre: '—' },
    we_trail: { key: '—', titre: '—' },
    ua: 440,
    decharge: true,
    objectif: '🏆 Senpereko Trail (14/03)',
    notes: 'Lundi récup post-cross, fin de semaine activation.',
  },
  {
    sem: 29,
    date: '15/03/2027',
    mois: 'Mars',
    phase: 'Récupération',
    phaseClass: 'phase-recup',
    mardi: { key: 'sortie_recup', titre: 'Sortie récupération active', terrain: 'halage' },
    jeudi: { key: 'fartlek', titre: 'Fartlek libre', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 500,
    decharge: true,
    objectif: null,
    notes: 'Récup post-courses. Reprise très progressive. Pas d\'intensité.',
  },
  {
    sem: 30,
    date: '22/03/2027',
    mois: 'Mars',
    phase: 'Base route',
    phaseClass: 'phase-base',
    mardi: { key: '1min30', titre: 'Efforts 1min30', terrain: 'halage' },
    jeudi: { key: '5min', titre: 'Efforts 5 minutes (seuil)', terrain: 'halage' },
    we_route: { key: 'allure_semi', titre: 'Sortie allure semi' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 830,
    decharge: false,
    objectif: null,
    notes: 'Pivot vers route. Allure semi sur sortie WE.',
  },
  {
    sem: 31,
    date: '29/03/2027',
    mois: 'Mars',
    phase: 'Spécifique',
    phaseClass: 'phase-precomp',
    mardi: { key: '5x1000_halage', titre: '5×1000m Halage R~2-3\'', terrain: 'halage' },
    jeudi: { key: 'cote_1min', titre: 'Côtes 1 minute — VW', terrain: 'vw' },
    we_route: { key: 'allure_semi', titre: 'Sortie allure semi' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 950,
    decharge: false,
    objectif: null,
    notes: 'Séance reine 5×1000m. Côtes maintenues pour la force.',
  },
  {
    sem: 32,
    date: '05/04/2027',
    mois: 'Avril',
    phase: 'Spécifique',
    phaseClass: 'phase-precomp',
    mardi: { key: '4x2000_r2', titre: '4×2000m R=2\'', terrain: 'halage' },
    jeudi: { key: 'fartlek_5_8_12_r3', titre: 'Fartlek progressif 5\'-8\'-12\' R=3\'', terrain: 'halage' },
    we_route: { key: 'allure_marathon', titre: 'Sortie allure marathon' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 1000,
    decharge: false,
    objectif: null,
    notes: 'Pic charge — 4×2000m + fartlek progressif. Test marathon Biarritz.',
  },
  {
    sem: 33,
    date: '12/04/2027',
    mois: 'Avril',
    phase: 'Compétition',
    phaseClass: 'phase-event',
    mardi: { key: '8x3_r130', titre: '8×3\' R=1\'30"', terrain: 'halage' },
    jeudi: { key: 'vitesse_5x100_veille', titre: '5×100m (séance veille de course)', terrain: 'stades' },
    we_route: { key: '—', titre: '—' },
    we_trail: { key: '—', titre: '—' },
    ua: 580,
    decharge: false,
    objectif: '🏆 Semi-Marathon Saint-Sébastien (18/04)',
    notes: 'Affûtage classique avant Semi.',
  },
  {
    sem: 34,
    date: '19/04/2027',
    mois: 'Avril',
    phase: 'Transition',
    phaseClass: 'phase-base',
    mardi: { key: 'fartlek_structure', titre: 'Fartlek structuré (2\'/2\')', terrain: 'halage' },
    jeudi: { key: '5x1000_halage', titre: '5×1000m Halage R~2-3\'', terrain: 'halage' },
    we_route: { key: 'allure_marathon', titre: 'Sortie allure marathon' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 760,
    decharge: false,
    objectif: null,
    notes: 'Transition courte. Une dernière séance allure marathon avant l\'affûtage.',
  },
  {
    sem: 35,
    date: '26/04/2027',
    mois: 'Avril',
    phase: 'Compétition',
    phaseClass: 'phase-event',
    mardi: { key: 'fartlek', titre: 'Fartlek libre', terrain: 'halage' },
    jeudi: { key: 'vitesse_5x100_veille', titre: '5×100m (séance veille de course)', terrain: 'stades' },
    we_route: { key: '—', titre: '—' },
    we_trail: { key: '—', titre: '—' },
    ua: 490,
    decharge: true,
    objectif: '🏆 Marathon Biarritz (02/05)',
    notes: 'Affûtage pur — intensité minimale.',
  },
  {
    sem: 36,
    date: '03/05/2027',
    mois: 'Mai',
    phase: 'Compétition',
    phaseClass: 'phase-event',
    mardi: { key: 'sortie_recup', titre: 'Sortie récupération active', terrain: 'halage' },
    jeudi: { key: 'vitesse_5x100_veille', titre: '5×100m (séance veille de course)', terrain: 'stades' },
    we_route: { key: '—', titre: '—' },
    we_trail: { key: '—', titre: '—' },
    ua: 420,
    decharge: true,
    objectif: '🏆 Euskal Raid (Ascension) (08/05)',
    notes: 'Récup post-marathon, activation jeudi.',
  },
  {
    sem: 37,
    date: '10/05/2027',
    mois: 'Mai',
    phase: 'Récupération',
    phaseClass: 'phase-recup',
    mardi: { key: '—', titre: '—', terrain: 'halage' },
    jeudi: { key: 'sortie_recup', titre: 'Sortie récupération active', terrain: 'halage' },
    we_route: { key: 'sortie_recup', titre: 'Sortie récupération active' },
    we_trail: { key: 'sortie_recup', titre: 'Sortie récupération active' },
    ua: 330,
    decharge: true,
    objectif: null,
    notes: 'Récup totale post-courses majeures. Footings très doux uniquement.',
  },
  {
    sem: 38,
    date: '17/05/2027',
    mois: 'Mai',
    phase: 'Base trail',
    phaseClass: 'phase-prepa',
    mardi: { key: 'cote_45s', titre: 'Côtes 12×45" — Floride ou VW', terrain: 'floride' },
    jeudi: { key: 'fartlek', titre: 'Fartlek libre', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 720,
    decharge: false,
    objectif: null,
    notes: 'Reprise trail — réintroduction côtes Floride/VW.',
  },
  {
    sem: 39,
    date: '24/05/2027',
    mois: 'Mai',
    phase: 'Développement',
    phaseClass: 'phase-dev',
    mardi: { key: 'cote_1min30', titre: 'Côtes 1min30 — VW ou Voulgre', terrain: 'voulgre' },
    jeudi: { key: '5min', titre: 'Efforts 5 minutes (seuil)', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 870,
    decharge: false,
    objectif: null,
    notes: 'Côtes VW/Voulgre — focus force aérobie pour trails été.',
  },
  {
    sem: 40,
    date: '31/05/2027',
    mois: 'Mai',
    phase: 'Spécifique trail',
    phaseClass: 'phase-prepa',
    mardi: { key: 'cote_2min', titre: 'Côtes 2 minutes — Voulgre', terrain: 'voulgre' },
    jeudi: { key: 'fartlek_pyramid_girouettes', titre: 'Pyramide 1\'2\'3\'4\'4\'4\'3\'2\'1\' Girouettes', terrain: 'girouettes' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 940,
    decharge: false,
    objectif: null,
    notes: 'Côtes Voulgre + pyramide Girouettes. Trail-spé pure.',
  },
  {
    sem: 41,
    date: '07/06/2027',
    mois: 'Juin',
    phase: 'Décharge',
    phaseClass: 'phase-recup',
    mardi: { key: 'fartlek', titre: 'Fartlek libre', terrain: 'halage' },
    jeudi: { key: 'sortie_recup', titre: 'Sortie récupération active', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 490,
    decharge: true,
    objectif: null,
    notes: 'Décharge mi-bloc trails.',
  },
  {
    sem: 42,
    date: '14/06/2027',
    mois: 'Juin',
    phase: 'Spécifique trail',
    phaseClass: 'phase-prepa',
    mardi: { key: 'cote_long', titre: 'Côtes longues 3-10min — montagne', terrain: 'montagne' },
    jeudi: { key: 'circuit_douves', titre: '6×Circuit Les Douves R=1\'30"', terrain: 'douves' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 960,
    decharge: false,
    objectif: null,
    notes: 'Côtes longues montagne (Ursuya/Mondarrain) + circuit Douves.',
  },
  {
    sem: 43,
    date: '21/06/2027',
    mois: 'Juin',
    phase: 'Spécifique trail',
    phaseClass: 'phase-prepa',
    mardi: { key: 'escaliers', titre: 'Escaliers — Côte des Basques', terrain: 'escaliers' },
    jeudi: { key: 'fartlek_pyramid_girouettes', titre: 'Pyramide 1\'2\'3\'4\'4\'4\'3\'2\'1\' Girouettes', terrain: 'girouettes' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 900,
    decharge: false,
    objectif: null,
    notes: 'Escaliers Côte des Basques + Girouettes. Travail descente excentrique.',
  },
  {
    sem: 44,
    date: '28/06/2027',
    mois: 'Juin',
    phase: 'Compétition',
    phaseClass: 'phase-event',
    mardi: { key: 'fartlek', titre: 'Fartlek libre', terrain: 'halage' },
    jeudi: { key: 'vitesse_5x100_veille', titre: '5×100m (séance veille de course)', terrain: 'stades' },
    we_route: { key: '—', titre: '—' },
    we_trail: { key: '—', titre: '—' },
    ua: 510,
    decharge: true,
    objectif: '🏆 Saison Trails Pays Basque (pic) (28/06)',
    notes: 'Forme optimale.',
  },
  {
    sem: 45,
    date: '05/07/2027',
    mois: 'Juill',
    phase: 'Décharge',
    phaseClass: 'phase-recup',
    mardi: { key: 'sortie_recup', titre: 'Sortie récupération active', terrain: 'halage' },
    jeudi: { key: 'fartlek', titre: 'Fartlek libre', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 490,
    decharge: true,
    objectif: null,
    notes: 'Décharge progressive — fin de saison se profile.',
  },
  {
    sem: 46,
    date: '12/07/2027',
    mois: 'Juill',
    phase: 'Reprise',
    phaseClass: 'phase-reprise',
    mardi: { key: 'cote_45s', titre: 'Côtes 12×45" — Floride ou VW', terrain: 'floride' },
    jeudi: { key: 'fartlek_structure', titre: 'Fartlek structuré (2\'/2\')', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 720,
    decharge: false,
    objectif: null,
    notes: 'Maintien de forme — intensité modérée. Volume modéré.',
  },
  {
    sem: 47,
    date: '19/07/2027',
    mois: 'Juill',
    phase: 'Décharge',
    phaseClass: 'phase-recup',
    mardi: { key: 'fartlek', titre: 'Fartlek libre', terrain: 'halage' },
    jeudi: { key: 'sortie_recup', titre: 'Sortie récupération active', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 470,
    decharge: true,
    objectif: null,
    notes: 'Décharge avant Fêtes de Bayonne.',
  },
  {
    sem: 48,
    date: '26/07/2027',
    mois: 'Juill',
    phase: 'Coupure',
    phaseClass: 'phase-recup',
    mardi: { key: '—', titre: '—', terrain: 'halage' },
    jeudi: { key: '—', titre: '—', terrain: 'halage' },
    we_route: { key: '—', titre: '—' },
    we_trail: { key: '—', titre: '—' },
    ua: 200,
    decharge: true,
    objectif: null,
    notes: '🎉 Fêtes de Bayonne — coupure totale. Bonne fête à tous !',
  },
  {
    sem: 49,
    date: '02/08/2027',
    mois: 'Août',
    phase: 'Reprise',
    phaseClass: 'phase-reprise',
    mardi: { key: '—', titre: '—', terrain: 'halage' },
    jeudi: { key: 'sortie_recup', titre: 'Sortie récupération active', terrain: 'halage' },
    we_route: { key: 'sortie_recup', titre: 'Sortie récupération active' },
    we_trail: { key: 'sortie_recup', titre: 'Sortie récupération active' },
    ua: 300,
    decharge: true,
    objectif: null,
    notes: 'Reprise très douce post-fêtes. Footings courts.',
  },
  {
    sem: 50,
    date: '09/08/2027',
    mois: 'Août',
    phase: 'Base',
    phaseClass: 'phase-base',
    mardi: { key: 'sortie_recup', titre: 'Sortie récupération active', terrain: 'halage' },
    jeudi: { key: 'fartlek', titre: 'Fartlek libre', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 500,
    decharge: true,
    objectif: null,
    notes: 'Reprise progressive — pas d\'intensité encore.',
  },
  {
    sem: 51,
    date: '16/08/2027',
    mois: 'Août',
    phase: 'Base',
    phaseClass: 'phase-base',
    mardi: { key: '30s', titre: 'Efforts 30 secondes (VMA courte)', terrain: 'halage' },
    jeudi: { key: '5min', titre: 'Efforts 5 minutes (seuil)', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 650,
    decharge: false,
    objectif: null,
    notes: 'Réintroduction VMA + seuil. Préparation rentrée.',
  },
  {
    sem: 52,
    date: '23/08/2027',
    mois: 'Août',
    phase: 'Base',
    phaseClass: 'phase-base',
    mardi: { key: 'cote_30s', titre: 'Côtes courtes 30s — La Floride', terrain: 'floride' },
    jeudi: { key: 'fartlek_10x1_1', titre: 'Fartlek 10×1\'/1\' (récup trottinée)', terrain: 'halage' },
    we_route: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    we_trail: { key: 'sortie_longue', titre: 'Sortie longue endurance' },
    ua: 780,
    decharge: false,
    objectif: null,
    notes: 'Fin de saison — préparation directe à la nouvelle saison qui commence S1.',
  },
]

// ── CALENDRIER FIXE (sorties section) ───────────────────────────
const calFixed = [
  {id:'f1', date:'2026-09-07',type:'social',   titre:'Reprise collective + BBQ',desc:'Reprise de saison au stade La Floride. Footing d\'accueil + BBQ de rentr\u00E9e. Anciens et nouveaux membres bienvenus.'},
  {id:'f2', date:'2026-09-21',type:'trail',    titre:'Sortie trail La Floride \u2192 Anglet',desc:'Sortie groupe trail mixte. D\u00E9part La Floride \u2192 Mousserolles \u2192 Les Girouettes \u2192 retour. ~2h. Tous niveaux.'},
  {id:'f3', date:'2026-10-05',type:'route',    titre:'Sortie longue route \u2014 Bayonne \u2192 Biarritz',desc:'Sortie longue dimanche matin. Bayonne \u2192 Anglet \u2192 Biarritz par la c\u00F4te \u2192 retour. ~2h. Allure EF.'},
  {id:'f4', date:'2026-10-12',type:'montagne', titre:'\uD83C\uDFD4 Sortie montagne \u2014 Ursuya',desc:'Groupe A : Ursuya depuis Sare (678m). Groupe B : c\u00F4tes VW + fartlek Bayonne. Retrouvailles au caf\u00E9.'},
  {id:'f5', date:'2026-10-26',type:'rando',    titre:'Rando Rhune \u2014 familles bienvenues',desc:'Rando conviviale sur la Rhune. Ouvert aux familles. Pique-nique au sommet. 3h30 aller-retour.'},
  {id:'f6', date:'2026-11-02',type:'trail',    titre:'Trail nocturne intra-muros Bayonne',desc:'Sortie nocturne dans Bayonne illumin\u00E9e. Lampes frontales obligatoires. Remparts \u2192 quais \u2192 citadelle. 1h30.'},
  {id:'f7', date:'2026-11-09',type:'montagne', titre:'\uD83C\uDFD4 Sortie montagne \u2014 Mondarrain',desc:'Mondarrain depuis Itxassou (749m). Groupe A : mont\u00E9es techniques. Groupe B : footing Bayonne.'},
  {id:'f8', date:'2026-12-07',type:'montagne', titre:'\uD83C\uDFD4 Sortie montagne hivernale \u2014 Ursuya',desc:'Ursuya en hiver. \u00C9quipement adapt\u00E9 requis. Brouillard basque et vues d\u00E9gag\u00E9es si chance.'},
  {id:'f9', date:'2026-12-21',type:'social',   titre:'Footing de No\u00EBl + repas section',desc:'Footing festif dans Bayonne illumin\u00E9e. Puis repas de section. Une tradition.'},
  {id:'f10',date:'2027-01-11',type:'montagne', titre:'\uD83C\uDFD4 Sortie montagne \u2014 Jaizkibel c\u00F4t\u00E9 espagnol',desc:'Monte Jaizkibel depuis Fontarrabie. Vue sur le Txingudi. ~3h. Covoiturage depuis La Floride (~35 min).'},
  {id:'f11',date:'2027-01-25',type:'route',    titre:'Sortie longue allure semi',desc:'Sortie pour ceux qui pr\u00E9parent un semi-marathon de printemps. 1h45 allure progressive.'},
  {id:'f12',date:'2027-02-08',type:'montagne', titre:'\uD83C\uDFD4 Sortie montagne \u2014 Artzamendi',desc:'Artzamendi depuis Itxassou. Circuit trail vari\u00E9. ~2h30. Mont\u00E9e r\u00E9guli\u00E8re, descente technique.'},
  {id:'f13',date:'2027-02-22',type:'rando',    titre:'Trek 2 jours \u2014 Voie de la Bidassoa',desc:'Weekend rando : vendredi soir \u2192 dimanche. Itin\u00E9raire sur la Bidassoa. H\u00E9bergement g\u00EEte.'},
  {id:'f14',date:'2027-03-22',type:'montagne', titre:'\uD83C\uDFD4 Sortie montagne \u2014 Mondarrain lever de soleil',desc:'Mont\u00E9e au Mondarrain pour le solstice de printemps. D\u00E9part 7h. Caf\u00E9 thermos obligatoire.'},
  {id:'f15',date:'2027-04-19',type:'montagne', titre:'\uD83C\uDFD4 Sortie Pyr\u00E9n\u00E9es \u2014 La Rhune',desc:'La Rhune depuis Col de Saint-Ignace. ~3h aller-retour. Vue Atlantique et Pyr\u00E9n\u00E9es. Tous niveaux trail.'},
  {id:'f16',date:'2027-06-06',type:'social',   titre:'Course d\'orientation intra-muros',desc:'Organisation interne : course d\'orientation dans le vieux Bayonne. \u00C9quipes mixtes, ouvert aux familles.'},
  {id:'f17',date:'2027-06-21',type:'montagne', titre:'\uD83C\uDFD4 Mondarrain au coucher de soleil',desc:'Mont\u00E9e pour le solstice d\'\u00E9t\u00E9. D\u00E9part 18h, coucher de soleil au sommet. Pique-nique partag\u00E9.'},
  {id:'f18',date:'2027-07-05',type:'montagne', titre:'\uD83C\uDFD4 Sortie Pyr\u00E9n\u00E9es \u2014 Pic d\'Orhy',desc:'Sortie niveau confirm\u00E9 : Pic d\'Orhy (2017m) depuis Larrau. ~5h AR. Covoiturage Bayonne.'},
  {id:'f19',date:'2027-07-19',type:'rando',    titre:'Trek 2 jours \u2014 Haute Soule',desc:'Bivouac 2 jours. Larrau \u2192 Iraty. Nuit en cabane. Inscription via bo\u00EEte \u00E0 id\u00E9es.'},
]

// ── CIRCUITS DE RENFORCEMENT ────────────────────────────────────
const circuits = {
  fondamental: {
    corpo: [
      { bloc:'\uD83D\uDD25 Activation (8 min)', exos:[
        {id:'squat_pc', dose:'2\u00D715 \u00B7 allure lente'},
        {id:'clamshell', dose:'2\u00D715 chaque c\u00F4t\u00E9'},
        {id:'cheville_proprio', dose:'2\u00D730 sec chaque'},
        {id:'planche', dose:'2\u00D730 sec'},
      ]},
      { bloc:'\uD83E\uDDB5 Force jambes (15 min)', exos:[
        {id:'step_up', dose:'3\u00D710 chaque \u00B7 3s descente'},
        {id:'step_down', dose:'3\u00D78 chaque \u00B7 4s descente'},
        {id:'fentes', dose:'3\u00D710 chaque'},
        {id:'glute_bridge', dose:'3\u00D712 chaque'},
      ]},
      { bloc:'\uD83E\uDDF1 Gainage (10 min)', exos:[
        {id:'dead_bug', dose:'3\u00D78 altern\u00E9s lents'},
        {id:'bird_dog', dose:'3\u00D78 altern\u00E9s \u00B7 pause 2s'},
        {id:'planche_lat', dose:'3\u00D730 sec chaque'},
      ]},
      { bloc:'\uD83D\uDC5F Mollets / cheville (7 min)', exos:[
        {id:'calf_raises', dose:'3\u00D715 \u00B7 complet'},
        {id:'tibialis', dose:'3\u00D720'},
      ]},
      { bloc:'\uD83C\uDF3F \u00C9tirements (5 min)', exos:[
        {id:'psoas', dose:'60 sec chaque'},
        {id:'ischios', dose:'60 sec chaque'},
        {id:'mollets_etirement', dose:'60 sec \u00D7 2 variantes'},
      ]}
    ],
    elastiques: [
      { bloc:'\uD83D\uDD25 Activation (8 min)', exos:[
        {id:'monster_walk', dose:'3\u00D710 pas chaque sens'},
        {id:'clamshell', dose:'3\u00D712 \u00B7 \u00E9lastique l\u00E9ger'},
        {id:'cheville_proprio', dose:'2\u00D730 sec chaque'},
      ]},
      { bloc:'\uD83E\uDDB5 Force jambes (15 min)', exos:[
        {id:'step_up', dose:'3\u00D710 chaque \u00B7 poids cheville'},
        {id:'step_down', dose:'3\u00D710 chaque \u00B7 4s \u00B7 poids cheville'},
        {id:'rdl_unipodal', dose:'3\u00D710 \u00B7 KB l\u00E9ger ou halt\u00E8re'},
        {id:'glute_bridge', dose:'3\u00D712 \u00B7 \u00E9lastique sur cuisses'},
      ]},
      { bloc:'\uD83E\uDDF1 Gainage (12 min)', exos:[
        {id:'dead_bug', dose:'3\u00D710 \u00B7 \u00E9lastique sur pied'},
        {id:'pallof_press', dose:'3\u00D710 chaque c\u00F4t\u00E9'},
        {id:'planche_lat', dose:'3\u00D735 sec chaque'},
        {id:'bird_dog', dose:'3\u00D710 \u00B7 poids cheville'},
      ]},
      { bloc:'\uD83D\uDC5F Mollets (7 min)', exos:[
        {id:'calf_raises', dose:'3\u00D715 \u00B7 marche \u00B7 poids cheville'},
        {id:'tibialis', dose:'3\u00D715 \u00B7 \u00E9lastique'},
        {id:'abducteurs_debout', dose:'3\u00D715 chaque \u00B7 \u00E9lastique'},
      ]},
      { bloc:'\uD83C\uDF3F \u00C9tirements (5 min)', exos:[
        {id:'psoas', dose:'60 sec chaque'},
        {id:'piriforme', dose:'60 sec chaque'},
        {id:'mollets_etirement', dose:'60 sec \u00D7 2 variantes'},
      ]}
    ],
    salle: [
      { bloc:'\uD83D\uDD25 Activation (8 min)', exos:[
        {id:'monster_walk', dose:'3\u00D710 pas \u00B7 \u00E9lastique fort'},
        {id:'abducteurs_debout', dose:'3\u00D715 chaque \u00B7 machine'},
        {id:'cheville_proprio', dose:'2\u00D730 sec chaque'},
      ]},
      { bloc:'\uD83E\uDDB5 Force jambes (20 min)', exos:[
        {id:'squat_pc', dose:'4\u00D712 \u00B7 goblet squat KB'},
        {id:'fentes', dose:'4\u00D710 chaque \u00B7 halt\u00E8res'},
        {id:'step_up', dose:'3\u00D710 chaque \u00B7 KB ou halt\u00E8res'},
        {id:'rdl_unipodal', dose:'3\u00D710 \u00B7 KB moyen'},
        {id:'leg_press', dose:'3\u00D712 unilat\u00E9ral'},
      ]},
      { bloc:'\uD83E\uDDF1 Gainage (12 min)', exos:[
        {id:'pallof_press', dose:'3\u00D710 chaque c\u00F4t\u00E9 \u00B7 c\u00E2ble'},
        {id:'dead_bug', dose:'3\u00D710 \u00B7 KB tenu'},
        {id:'planche_lat', dose:'3\u00D735 sec chaque'},
      ]},
      { bloc:'\uD83D\uDC5F Mollets (8 min)', exos:[
        {id:'calf_raises', dose:'4\u00D715 \u00B7 KB lourd \u00B7 marche'},
        {id:'tibialis', dose:'3\u00D715 \u00B7 machine ou disque'},
        {id:'glute_bridge', dose:'4\u00D712 \u00B7 hip thrust barre l\u00E9g\u00E8re'},
      ]},
      { bloc:'\uD83C\uDF3F \u00C9tirements (5 min)', exos:[
        {id:'psoas', dose:'60 sec chaque'},
        {id:'piriforme', dose:'60 sec chaque'},
        {id:'bandelette', dose:'60 sec chaque \u00B7 foam roller'},
      ]}
    ]
  },
  force: {
    corpo: [
      { bloc:'\uD83D\uDD25 Activation (8 min)', exos:[
        {id:'clamshell', dose:'2\u00D715 \u00B7 lent'},
        {id:'monster_walk', dose:'2\u00D710 pas chaque sens'},
        {id:'squat_pc', dose:'2\u00D710 \u00B7 3s descente excentrique'},
      ]},
      { bloc:'\uD83E\uDDB5 Force maximale (20 min)', exos:[
        {id:'squat_unipodal', dose:'4\u00D78 chaque \u00B7 4s descente'},
        {id:'step_down', dose:'4\u00D710 chaque \u00B7 5s excentrique'},
        {id:'fentes', dose:'4\u00D78 chaque \u00B7 3s excentrique'},
        {id:'rdl_unipodal', dose:'3\u00D710 chaque \u00B7 lent'},
      ]},
      { bloc:'\uD83E\uDDF1 Gainage lourd (12 min)', exos:[
        {id:'planche', dose:'4\u00D750 sec'},
        {id:'planche_lat', dose:'3\u00D740 sec + 10 dips'},
        {id:'pallof_press', dose:'Sans \u00E9quip : planche rotative'},
      ]},
      { bloc:'\uD83D\uDC5F Mollets intensif (8 min)', exos:[
        {id:'calf_raises', dose:'4\u00D720 \u00B7 amplitude max'},
        {id:'tibialis', dose:'3\u00D720'},
      ]},
      { bloc:'\uD83C\uDF3F \u00C9tirements (5 min)', exos:[
        {id:'psoas', dose:'90 sec chaque'},
        {id:'ischios', dose:'90 sec chaque'},
        {id:'piriforme', dose:'60 sec chaque'},
      ]}
    ],
    elastiques: [
      { bloc:'\uD83D\uDD25 Activation (8 min)', exos:[
        {id:'monster_walk', dose:'3\u00D712 \u00B7 \u00E9lastique fort aux chevilles'},
        {id:'clamshell', dose:'3\u00D712 \u00B7 \u00E9lastique fort'},
        {id:'abducteurs_debout', dose:'3\u00D712 chaque \u00B7 \u00E9lastique'},
      ]},
      { bloc:'\uD83E\uDDB5 Force (20 min)', exos:[
        {id:'squat_unipodal', dose:'4\u00D78 \u00B7 4s excentrique \u00B7 poids cheville'},
        {id:'step_down', dose:'4\u00D710 \u00B7 5s \u00B7 poids cheville'},
        {id:'rdl_unipodal', dose:'4\u00D710 \u00B7 KB moyen'},
        {id:'fentes', dose:'4\u00D78 chaque \u00B7 poids cheville'},
      ]},
      { bloc:'\uD83E\uDDF1 Gainage (12 min)', exos:[
        {id:'pallof_press', dose:'4\u00D710 chaque \u00B7 \u00E9lastique fort'},
        {id:'dead_bug', dose:'3\u00D712 \u00B7 poids cheville'},
        {id:'planche_lat', dose:'3\u00D745 sec + dips'},
      ]},
      { bloc:'\uD83D\uDC5F Mollets (8 min)', exos:[
        {id:'calf_raises', dose:'4\u00D715 \u00B7 poids cheville \u00B7 marche'},
        {id:'tibialis', dose:'3\u00D720 \u00B7 \u00E9lastique'},
        {id:'glute_bridge', dose:'3\u00D712 \u00B7 \u00E9lastique sur cuisses \u00B7 poids sur bassin'},
      ]},
      { bloc:'\uD83C\uDF3F \u00C9tirements', exos:[
        {id:'psoas', dose:'90 sec chaque'},
        {id:'ischios', dose:'\u00E9lastique \u00B7 90 sec chaque'},
        {id:'bandelette', dose:'60 sec chaque'},
      ]}
    ],
    salle: [
      { bloc:'\uD83D\uDD25 Activation (8 min)', exos:[
        {id:'monster_walk', dose:'3\u00D712 \u00B7 \u00E9lastique fort'},
        {id:'hip_thrust', dose:'2\u00D715 \u00B7 barre l\u00E9g\u00E8re \u00B7 activation'},
      ]},
      { bloc:'\uD83E\uDDB5 Force maximale (25 min)', exos:[
        {id:'squat_pc', dose:'5\u00D75 \u00B7 back squat charg\u00E9 \u00B7 3s excentrique'},
        {id:'fentes', dose:'4\u00D78 chaque \u00B7 barre ou KB lourds'},
        {id:'step_down', dose:'4\u00D710 \u00B7 5s \u00B7 KB lourd'},
        {id:'rdl_unipodal', dose:'4\u00D78 \u00B7 barre ou KB lourd'},
        {id:'leg_press', dose:'4\u00D710 \u00B7 charg\u00E9 \u00B7 unilat\u00E9ral'},
      ]},
      { bloc:'\uD83C\uDF51 Fessiers (10 min)', exos:[
        {id:'hip_thrust', dose:'4\u00D710 \u00B7 barre charg\u00E9e'},
        {id:'abducteurs_debout', dose:'3\u00D715 \u00B7 machine'},
      ]},
      { bloc:'\uD83D\uDC5F Mollets (8 min)', exos:[
        {id:'calf_raises', dose:'5\u00D715 \u00B7 machine charg\u00E9e'},
        {id:'tibialis', dose:'3\u00D715 \u00B7 machine'},
      ]},
      { bloc:'\uD83C\uDF3F \u00C9tirements', exos:[
        {id:'psoas', dose:'90 sec chaque'},
        {id:'ischios', dose:'90 sec chaque'},
        {id:'bandelette', dose:'foam roller \u00B7 90 sec chaque'},
      ]}
    ]
  },
  specifique: {
    corpo: [
      { bloc:'\uD83D\uDD25 Activation (8 min)', exos:[
        {id:'squat_jump', dose:'2\u00D76 \u00B7 l\u00E9ger \u00B7 allumage'},
        {id:'clamshell', dose:'2\u00D712 \u00B7 lent'},
        {id:'cheville_proprio', dose:'2\u00D730 sec'},
      ]},
      { bloc:'\u26A1 Pliom\u00E9trie trail (15 min)', exos:[
        {id:'squat_jump', dose:'4\u00D78 \u00B7 puissants'},
        {id:'bounding', dose:'4\u00D710 aller-retour'},
        {id:'drop_jump', dose:'3\u00D78 \u00B7 box 20cm'},
      ]},
      { bloc:'\uD83E\uDDB5 Force unilat\u00E9rale (12 min)', exos:[
        {id:'squat_unipodal', dose:'3\u00D78 chaque \u00B7 lent'},
        {id:'step_down', dose:'3\u00D710 \u00B7 5s excentrique'},
        {id:'rdl_unipodal', dose:'3\u00D710 chaque'},
      ]},
      { bloc:'\uD83D\uDC5F Mollets & cheville (8 min)', exos:[
        {id:'calf_raises', dose:'3\u00D720 \u00B7 amplitude max'},
        {id:'cheville_proprio', dose:'3\u00D730 sec \u00B7 yeux ferm\u00E9s'},
      ]},
      { bloc:'\uD83C\uDF3F \u00C9tirements (7 min)', exos:[
        {id:'psoas', dose:'60 sec chaque'},
        {id:'piriforme', dose:'60 sec chaque'},
        {id:'mollets_etirement', dose:'60 sec \u00D7 2 variantes'},
      ]}
    ],
    elastiques: [
      { bloc:'\uD83D\uDD25 Activation (8 min)', exos:[
        {id:'monster_walk', dose:'3\u00D710 pas \u00B7 \u00E9lastique'},
        {id:'bounding', dose:'2\u00D78 \u00B7 activation'},
      ]},
      { bloc:'\u26A1 Pliom\u00E9trie (15 min)', exos:[
        {id:'squat_jump', dose:'4\u00D78'},
        {id:'bounding', dose:'4\u00D710 AR \u00B7 poids cheville'},
        {id:'drop_jump', dose:'3\u00D78'},
      ]},
      { bloc:'\uD83E\uDDB5 Force (12 min)', exos:[
        {id:'squat_unipodal', dose:'3\u00D78 \u00B7 poids cheville'},
        {id:'step_down', dose:'3\u00D710 \u00B7 poids cheville \u00B7 5s'},
        {id:'rdl_unipodal', dose:'3\u00D710 \u00B7 KB'},
      ]},
      { bloc:'\uD83E\uDDF1 Gainage anti-rotation (8 min)', exos:[
        {id:'pallof_press', dose:'4\u00D710 chaque \u00B7 \u00E9lastique'},
        {id:'planche_lat', dose:'3\u00D740 sec + dips'},
      ]},
      { bloc:'\uD83C\uDF3F \u00C9tirements', exos:[
        {id:'psoas', dose:'60 sec chaque'},
        {id:'ischios', dose:'\u00E9lastique \u00B7 60 sec chaque'},
        {id:'bandelette', dose:'60 sec chaque'},
      ]}
    ],
    salle: [
      { bloc:'\uD83D\uDD25 Activation (8 min)', exos:[
        {id:'monster_walk', dose:'3\u00D712 \u00B7 fort'},
        {id:'hip_thrust', dose:'2\u00D715 \u00B7 activation l\u00E9g\u00E8re'},
      ]},
      { bloc:'\u26A1 Pliom\u00E9trie (15 min)', exos:[
        {id:'box_jump', dose:'4\u00D76 \u00B7 box 40cm'},
        {id:'squat_jump', dose:'3\u00D78 \u00B7 gilet lest\u00E9 l\u00E9ger'},
        {id:'drop_jump', dose:'3\u00D76 \u00B7 box 30cm'},
        {id:'bounding', dose:'3\u00D710 AR'},
      ]},
      { bloc:'\uD83E\uDDB5 Force sp\u00E9cifique (15 min)', exos:[
        {id:'squat_unipodal', dose:'3\u00D78 \u00B7 KB \u00B7 4s excentrique'},
        {id:'rdl_unipodal', dose:'3\u00D710 \u00B7 KB lourd'},
        {id:'hip_thrust', dose:'3\u00D710 \u00B7 barre charg\u00E9e'},
      ]},
      { bloc:'\uD83D\uDC5F Mollets (8 min)', exos:[
        {id:'calf_raises', dose:'4\u00D715 \u00B7 machine charg\u00E9e'},
        {id:'tibialis', dose:'3\u00D715 \u00B7 machine'},
      ]},
      { bloc:'\uD83C\uDF3F \u00C9tirements', exos:[
        {id:'psoas', dose:'60 sec chaque'},
        {id:'piriforme', dose:'60 sec chaque'},
        {id:'bandelette', dose:'foam roller \u00B7 90 sec'},
      ]}
    ]
  },
  competition: {
    corpo: [
      { bloc:'\u26A1 Activation + vivacit\u00E9 (10 min)', exos:[
        {id:'squat_jump', dose:'2\u00D76 \u00B7 l\u00E9ger'},
        {id:'bounding', dose:'2\u00D78 aller-retour'},
        {id:'clamshell', dose:'2\u00D712 chaque'},
        {id:'cheville_proprio', dose:'2\u00D730 sec'},
      ]},
      { bloc:'\uD83E\uDDB5 Entretien force (12 min)', exos:[
        {id:'step_down', dose:'3\u00D78 \u00B7 4s excentrique'},
        {id:'glute_bridge', dose:'3\u00D710 chaque'},
        {id:'rdl_unipodal', dose:'3\u00D78 \u00B7 l\u00E9ger'},
      ]},
      { bloc:'\uD83D\uDC5F Mollets & pr\u00E9vention (8 min)', exos:[
        {id:'calf_raises', dose:'3\u00D715'},
        {id:'tibialis', dose:'3\u00D720'},
        {id:'cheville_proprio', dose:'2\u00D730 sec yeux ferm\u00E9s'},
      ]},
      { bloc:'\uD83C\uDF3F \u00C9tirements (10 min)', exos:[
        {id:'psoas', dose:'90 sec chaque'},
        {id:'ischios', dose:'90 sec chaque'},
        {id:'piriforme', dose:'60 sec chaque'},
        {id:'mollets_etirement', dose:'60 sec \u00D7 2'},
      ]}
    ],
    elastiques: [
      { bloc:'\u26A1 Activation (10 min)', exos:[
        {id:'monster_walk', dose:'2\u00D710 \u00B7 \u00E9lastique l\u00E9ger'},
        {id:'squat_jump', dose:'2\u00D76'},
        {id:'bounding', dose:'2\u00D78 AR'},
      ]},
      { bloc:'\uD83E\uDDB5 Entretien (12 min)', exos:[
        {id:'step_down', dose:'3\u00D78 \u00B7 poids cheville \u00B7 4s'},
        {id:'rdl_unipodal', dose:'3\u00D78 \u00B7 KB l\u00E9ger'},
        {id:'clamshell', dose:'3\u00D712 \u00B7 \u00E9lastique'},
      ]},
      { bloc:'\uD83D\uDC5F Mollets (8 min)', exos:[
        {id:'calf_raises', dose:'3\u00D715 \u00B7 poids cheville'},
        {id:'cheville_proprio', dose:'3\u00D730 sec'},
      ]},
      { bloc:'\uD83C\uDF3F \u00C9tirements', exos:[
        {id:'psoas', dose:'90 sec chaque'},
        {id:'piriforme', dose:'60 sec chaque'},
        {id:'bandelette', dose:'foam roller \u00B7 60 sec'},
      ]}
    ],
    salle: [
      { bloc:'\u26A1 Activation + pliom\u00E9trie l\u00E9g\u00E8re (10 min)', exos:[
        {id:'box_jump', dose:'2\u00D75 \u00B7 box basse'},
        {id:'monster_walk', dose:'2\u00D710 \u00B7 fort'},
        {id:'bounding', dose:'2\u00D78 AR'},
      ]},
      { bloc:'\uD83E\uDDB5 Entretien force (15 min)', exos:[
        {id:'squat_unipodal', dose:'3\u00D76 \u00B7 KB \u00B7 mod\u00E9r\u00E9'},
        {id:'rdl_unipodal', dose:'3\u00D78 \u00B7 KB moyen'},
        {id:'hip_thrust', dose:'3\u00D710 \u00B7 mod\u00E9r\u00E9'},
      ]},
      { bloc:'\uD83D\uDC5F Mollets (8 min)', exos:[
        {id:'calf_raises', dose:'3\u00D715 \u00B7 machine charg\u00E9e'},
        {id:'tibialis', dose:'3\u00D715'},
      ]},
      { bloc:'\uD83C\uDF3F \u00C9tirements', exos:[
        {id:'psoas', dose:'90 sec chaque'},
        {id:'ischios', dose:'90 sec chaque'},
        {id:'bandelette', dose:'foam roller \u00B7 90 sec'},
      ]}
    ]
  }
}
